### ISSUE TITLE
`스프링부트에 패스워드 암호화 적용하기` 오류

### ISSUE THREAD

**Issue by ImSejin** [youngjinmo/youngjinmo.github.io#1]
안녕하세요, 영진님
[포스트](https://youngjinmo.github.io/2021/05/passwordencoder/#Spring-Security-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85) 보다가 잘못된 부분이 있더라고요.

```text
버전을 명시하지 않고 주입하면 IDE에서 자동으로 최신 버전을 가져올 이다.
```

parent pom.xml에 명시한 버전을 가져오는 것이지, IDE와는 아무런 관련이 없어요.
- - -
P.S 블로그에 댓글로 남기려고 했는데 [utterances](https://github.com/utterance/utterances)를 설치하지 않아서 직접 issue 남겨요.

**Comment by youngjinmo** [comment]
앗. 제가 빌드 툴에 대한 이해도가 부족해서 그렇게 작성했던것 같습니다..!
알려주셔서 감사합니다!! :)
그리고 깃헙 계정연동하면 utterance 사용이 가능하셨을텐데, 혹시 다른 문제가 있었을까요..?

**Comment by youngjinmo** [comment]
아 그리고 포스팅 수정하면서 세진님을 인용해도 괜찮을까요..?
깃헙 프로필을 링크해서 `세진님으로부터 피드백을 받아 수정하였습니다.` 식으로 수정하려고 합니다..^^

**Comment by ImSejin** [comment]
@youngjinmo 

아래처럼 뜹니다. [여기](https://github.com/apps/utterances)에서 설치하시면 될 거 같아요.

![image](https://user-images.githubusercontent.com/46176032/123230421-32013680-d512-11eb-9d3f-967a3b50d4cc.png)

- - -

네, 인용하셔도 좋습니다!

**Comment by youngjinmo** [comment]
헉.. 언제부터 이랬던거지...
너무 감사합니다..!!

**Comment by youngjinmo** [comment]
아래의 내용을 블로그에 추가하려고 하는데, 잠깐 찾아본 수준이라 혹시 이렇게 이해한게 맞을까요..?
마지막으로 피드백 부탁드립니다..^^

메이븐 기준으로 parent는 아래의 예제에 해당 된다.

~~~properties
<parent>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-parent</artifactId>
   <version>2.0.5.RELEASE</version>
   <relativePath/>
</parent>
~~~

하위 계층의 라이브러리를 사용할때 버전을 명시하지 않으면 위의 parent에서 명시한 `spring-boot-starter-parent`에 명시된 버전을 가져오게 된다.

**Comment by ImSejin** [comment]
정확히 하자면 `spring-boot-starter-parent`에 명시된 건 아니고요.
`spring-boot-starter-parent`의 부모인 `spring-boot-dependencies`에 모든 dependencies이 명시되어 있습니다.

version을 명시하지 않으면 여기에 명시된 version의 dependency를 사용하는 거죠.

**Comment by youngjinmo** [comment]
피드백 감사합니다..! 궁금한게 더 있지만.. 더이상 여쭙기보다 각잡고 빌드툴을 공부해봐야겠네요..!
업무시간임에도 블로그 피드백도 주시고 버그(utterances)도 제보해주셔서 감사합니다! 
추가로 답변주신것까지 인용해서 포스팅 업데이트하겠습니다 ㅎㅎ
